name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the lobby Docker image
      run: docker build . --file Dockerfile --tag corysanin/forbidden-game:lobby-latest
    - name: Build the game Docker image
      run: docker build game-server --file game-server/Dockerfile --tag corysanin/forbidden-game:game-latest
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin; docker push "corysanin/forbidden-game:lobby-latest"; docker push "corysanin/forbidden-game:game-latest"
    
